FROM ubuntu:19.10

RUN apt-get update

RUN apt-get upgrade -y

RUN apt-get install -y cmake ninja-build build-essential \
            python3 python3-dev python3-pip \
            libedit-dev libedit2 tmux ccache swig \
            openssh-server git vim man

RUN git clone --bare https://github.com/llvm/llvm-project.git ~/llvm-project.git
